language: php
php:
  - 7.0
script:
  - composer install
  - bin/phpspec run
after_script:
  - bin/test-reporter
addons:
  code_climate:
    repo_token: 57587da2349a2bc47550cfbad3091ff5612ae18814c28a84b6c490006862c23f
